# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: "14"
#      - name: Install dependencies
#        run: yarn install
#      - name: build example
#        run: |
#          yarn build-example
#          echo "the pwd directory: `pwd`"
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.PRIVATE_DEPLOY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "github.com" >> ~/.ssh/known_hosts
          echo "---------- set ssh-key ok ----------"
      - name: download and replace # 下载现有文件，替换
        run: |
          git clone git@github.com:psybor/psybor.github.io.git
          echo "---------- git clone ok ----------"
          rm -rf ./psybor.github.io/*
          cd psybor.github.io
          echo "the pwd directory: `pwd`"
#          cp -r ./_book/* ./psybor.github.io ## 用最新构建出来的文件，替换现有的
#          echo "---------- replace ok ----------"
#      - name: upload # 上传文件
#        run: |
#          cd ./psybor.github.io
#          git config user.name "github-actions"
#          git config user.email "github-actions@github.com"
#          echo "---------- begin git status ----------"
#          echo `git status`
#          echo "---------- end git status ----------"
#          git add .
#          git commit -m "update by github actions"
#          git push origin main
#      - name: delete ssh key # 删除 ssh key
#        run: rm -rf ~/.ssh/id_rsa
